# parameters for MBRA
context_size: 5 #history of image
len_traj_pred: 8 #action length
learn_angle: True
obs_encoder: efficientnet-b0
obs_encoding_size: 1024
late_fusion: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
